const $=id=>document.getElementById(id);
const video=$('video'),arCanvas=$('arCanvas'),renderCanvas=$('renderCanvas'),status=$('status'),lensName=$('lensName'),filtersEl=$('filters'),arBadge=$('arBadge');
let stream=null,facing='user',active='normal',landmarker=null,lastVideoTime=-1,faceResult=null,tracking=true,mirror=true,photoMode=true,recorder=null,recordingChunks=[],installPrompt=null,raf=0;
const lenses=[
 ['normal','Natural',''],['bw','Mono','◐'],['warm','Warm','☀'],['cool','Cool','❄'],['neon','Neon','✦'],['cinematic','Cine','▣'],['sunset','Sunset','◒'],['glow','Glow','✧'],['vhs','VHS','▤'],
 ['glasses','Shades','😎'],['crown','Crown','♛'],['ears','Bunny','🐰'],['sparkle','Sparkles','✦'],['mask','Mask','◉'],['invert','X-Ray','◌']
];
function renderFilters(){filtersEl.innerHTML=lenses.map(([id,name,icon])=>`<button class="filter ${id===active?'active':''}" data-id="${id}"><b class="icon">${icon}</b><span>${name}</span></button>`).join('');filtersEl.querySelectorAll('.filter').forEach(b=>b.onclick=()=>setLens(b.dataset.id));}
const AR_LENSES=['glasses','crown','ears','sparkle','mask'];
function setLens(id){active=id;const l=lenses.find(x=>x[0]===id);lensName.textContent=l?.[1]||'Natural';video.className=`filter-${id}`;arBadge.textContent=AR_LENSES.includes(id)?'AR ON':'LENS';arBadge.classList.toggle('on',true);renderFilters();if(AR_LENSES.includes(id)){initAR()}else{faceResult=null;try{arCanvas.getContext('2d').clearRect(0,0,arCanvas.width,arCanvas.height)}catch{}}}
function resize(){const r=arCanvas.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);arCanvas.width=Math.max(1,r.width*d);arCanvas.height=Math.max(1,r.height*d);renderCanvas.width=video.videoWidth||1080;renderCanvas.height=video.videoHeight||1920;}
window.addEventListener('resize',resize);
async function startCamera(){
  if(!navigator.mediaDevices?.getUserMedia){status.style.display='block';status.textContent='Camera access requires a modern HTTPS browser.';return;}
  if(stream){stream.getTracks().forEach(t=>{try{t.stop()}catch{}});stream=null;}
  video.pause();video.srcObject=null;
  const base={video:{facingMode:{ideal:facing},width:{ideal:720},height:{ideal:1280},frameRate:{ideal:30,max:30}},audio:false};
  try{
    stream=await navigator.mediaDevices.getUserMedia(base);
    video.muted=true;video.playsInline=true;video.autoplay=true;video.srcObject=stream;
    video.onloadedmetadata=async()=>{resize();status.style.display='none';try{await video.play()}catch{};initAR()};
    $('recordStatus').textContent='Camera is ready. Microphone is off for stability.';
  }catch(e){
    if(stream){stream.getTracks().forEach(t=>{try{t.stop()}catch{}});stream=null;}
    status.style.display='block';
    const name=e?.name||'';
    status.textContent=name==='NotAllowedError'?'Camera permission was denied. Allow camera access in Chrome site settings.':name==='NotFoundError'?'No camera was found on this device.':name==='NotReadableError'?'Android could not start the camera. Close other camera apps and try again.':'LeonLens could not start the camera. Try Chrome or reload the page.';
    console.error('LeonLens camera error',e);
  }
}
async function initAR(){if(!tracking||!window.vision||!AR_LENSES.includes(active))return;try{const {FaceLandmarker,FilesetResolver}=window.vision;if(!landmarker){const fs=await FilesetResolver.forVisionTasks('https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.22/wasm');landmarker=await FaceLandmarker.createFromOptions(fs,{baseOptions:{modelAssetPath:'https://storage.googleapis.com/mediapipe-models/face_landmarker/face_landmarker/float16/1/face_landmarker.task'},runningMode:'VIDEO',numFaces:1,minFaceDetectionConfidence:.5,minFacePresenceConfidence:.5,minTrackingConfidence:.5,outputFaceBlendshapes:false});}cancelAnimationFrame(raf);raf=requestAnimationFrame(track);}catch(e){console.warn(e);if($('recordStatus'))$('recordStatus').textContent='AR effects need an internet connection the first time they load.';}}
let lastDetect=0;function track(){if(!AR_LENSES.includes(active)){raf=0;return}const now=performance.now();if(video.readyState>=2&&landmarker&&video.currentTime!==lastVideoTime&&now-lastDetect>100){lastVideoTime=video.currentTime;lastDetect=now;try{faceResult=landmarker.detectForVideo(video,now);}catch(e){}}drawAR();raf=requestAnimationFrame(track);}
function pt(l,i){const p=l[i];return{x:p.x*arCanvas.width,y:p.y*arCanvas.height}}
function drawAR(ctx=arCanvas.getContext('2d')){ctx.clearRect(0,0,arCanvas.width,arCanvas.height);if(!tracking||!faceResult?.faceLandmarks?.length)return;const l=faceResult.faceLandmarks[0],left=pt(l,33),right=pt(l,263),nose=pt(l,1),top=pt(l,10),chin=pt(l,152),scale=Math.hypot(right.x-left.x,right.y-left.y),angle=Math.atan2(right.y-left.y,right.x-left.x);ctx.save();ctx.translate(nose.x,nose.y);ctx.rotate(angle);ctx.textAlign='center';ctx.textBaseline='middle';
 if(active==='glasses'){const w=scale*1.55,h=scale*.43;ctx.fillStyle='#111d';ctx.strokeStyle='#fff';ctx.lineWidth=Math.max(2,scale*.025);for(const x of[-w*.28,w*.28]){ctx.beginPath();ctx.roundRect(x-w*.28,-h/2,w*.56,h, h*.25);ctx.fill();ctx.stroke();}ctx.beginPath();ctx.moveTo(-w*.03,0);ctx.lineTo(w*.03,0);ctx.stroke();}
 if(active==='crown'){ctx.fillStyle='#ffd83d';ctx.strokeStyle='#fff';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(-scale*.7,-scale*.55);ctx.lineTo(-scale*.42,-scale*1.05);ctx.lineTo(-scale*.08,-scale*.65);ctx.lineTo(scale*.25,-scale*1.08);ctx.lineTo(scale*.7,-scale*.55);ctx.lineTo(scale*.58,-scale*.2);ctx.lineTo(-scale*.58,-scale*.2);ctx.closePath();ctx.fill();ctx.stroke();}
 if(active==='ears'){ctx.fillStyle='#f3b5d3';for(const x of[-scale*.55,scale*.55]){ctx.beginPath();ctx.ellipse(x,-scale*.65,scale*.28,scale*.6,x<0?-.3:.3,0,Math.PI*2);ctx.fill();}ctx.fillStyle='#fff';for(const x of[-scale*.55,scale*.55]){ctx.beginPath();ctx.ellipse(x,-scale*.65,scale*.12,scale*.38,x<0?-.3:.3,0,Math.PI*2);ctx.fill();}}
 if(active==='sparkle'){ctx.fillStyle='#fff';[[-.8,-.55],[.8,-.35],[-.65,.35],[.72,.42]].forEach(([x,y],i)=>{const s=scale*(i%2?.12:.16);ctx.beginPath();ctx.moveTo(x*scale,y*scale-s);ctx.lineTo(x*scale+s*.25,y*scale);ctx.lineTo(x*scale,y*scale+s);ctx.lineTo(x*scale-s*.25,y*scale);ctx.closePath();ctx.fill();});}
 if(active==='mask'){ctx.fillStyle='rgba(28,25,50,.78)';ctx.strokeStyle='#fff';ctx.lineWidth=2;ctx.beginPath();ctx.ellipse(0,scale*.25,scale*.62,scale*.34,0,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillStyle='#fff';ctx.font=`${Math.max(14,scale*.18)}px system-ui`;ctx.fillText('LEON',0,scale*.25);}
 ctx.restore();}
function drawComposite(){const c=renderCanvas,ctx=c.getContext('2d');const w=video.videoWidth,h=video.videoHeight;if(!w||!h)return false;c.width=w;c.height=h;ctx.save();ctx.filter=getComputedStyle(video).filter;if(mirror&&facing==='user'){ctx.translate(w,0);ctx.scale(-1,1)}ctx.drawImage(video,0,0,w,h);ctx.restore();if(tracking&&faceResult?.faceLandmarks?.length){const temp=document.createElement('canvas');temp.width=arCanvas.width;temp.height=arCanvas.height;const t=temp.getContext('2d');drawAR(t);ctx.drawImage(temp,0,0,w,h);}return true;}
function downloadBlob(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},1500)}
async function capture(){if(!drawComposite())return;renderCanvas.toBlob(blob=>{if(blob){downloadBlob(blob,`leonlens-${Date.now()}.jpg`);saveMemory(blob,'image');flashEffect();}},'image/jpeg',.92)}
function flashEffect(){document.body.classList.add('flash-on');setTimeout(()=>document.body.classList.remove('flash-on'),160)}
function startRecording(){if(recorder?.state==='recording'){recorder.stop();return}if(!stream||!renderCanvas.captureStream){$('recordStatus').textContent='Video recording is not supported in this browser.';return}recordingChunks=[];const compositeStream=renderCanvas.captureStream(30);const tracks=stream.getAudioTracks();tracks.forEach(t=>compositeStream.addTrack(t));let mime='video/webm;codecs=vp9';if(!MediaRecorder.isTypeSupported(mime))mime='video/webm';try{recorder=new MediaRecorder(compositeStream,{mimeType:mime});recorder.ondataavailable=e=>e.data.size&&recordingChunks.push(e.data);recorder.onstop=()=>{const blob=new Blob(recordingChunks,{type:mime});downloadBlob(blob,`leonlens-video-${Date.now()}.webm`);saveMemory(blob,'video');$('recordBtn').classList.remove('recording');$('recordStatus').textContent='Video saved to Memories.';};recorder.start(250);$('recordBtn').classList.add('recording');$('recordStatus').textContent='Recording… tap the red button to stop.';recordCompositeLoop();}catch(e){$('recordStatus').textContent='Recording could not start.'}}
let compositeRaf=0;function recordCompositeLoop(){if(recorder?.state!=='recording')return;drawComposite();compositeRaf=requestAnimationFrame(recordCompositeLoop)}
function saveMemory(blob,type){const r=new FileReader();r.onload=()=>{try{const items=JSON.parse(localStorage.getItem('leonlens_memories')||'[]');items.unshift({id:Date.now(),type,data:r.result});const kept=items.slice(0,30);while(kept.length){try{localStorage.setItem('leonlens_memories',JSON.stringify(kept));break}catch{kept.pop()}}}catch{}};r.readAsDataURL(blob)}
function openGallery(){renderGallery();$('gallery').classList.add('open')}
function renderGallery(){const grid=$('galleryGrid'),empty=$('emptyGallery');let items=[];try{items=JSON.parse(localStorage.getItem('leonlens_memories')||'[]')}catch{}grid.innerHTML='';empty.style.display=items.length?'none':'block';items.forEach(item=>{const el=document.createElement('div');el.className='gallery-item';el.innerHTML=item.type==='image'?`<img src="${item.data}" loading="lazy"><button aria-label="Delete">×</button>`:`<video src="${item.data}" controls playsinline></video><button aria-label="Delete">×</button>`;el.querySelector('button').onclick=()=>{const next=items.filter(x=>x.id!==item.id);localStorage.setItem('leonlens_memories',JSON.stringify(next));renderGallery()};grid.appendChild(el);});}
function closePanels(){$$('.panel').forEach(p=>p.classList.remove('open'))}function $$(s){return [...document.querySelectorAll(s)]}
$('flip').onclick=()=>{if(!stream)return;facing=facing==='user'?'environment':'user';startCamera()};$('flash').onclick=async()=>{const track=stream?.getVideoTracks()[0],caps=track?.getCapabilities?.();if(caps?.torch){try{await track.applyConstraints({advanced:[{torch:!document.body.classList.contains('torch-on')}]});document.body.classList.toggle('torch-on')}catch{ $('recordStatus').textContent='Torch control failed on this device/browser.'; }}else{$('recordStatus').textContent='Torch control is not available on this device/browser.';flashEffect()}};
$('capture').onclick=()=>photoMode?capture():startRecording();$('recordBtn').onclick=startRecording;$('upload').onclick=()=>$('file').click();$('file').onchange=e=>{const f=e.target.files?.[0];if(!f)return;const url=URL.createObjectURL(f);if(f.type.startsWith('video/')){video.srcObject=null;video.src=url;video.muted=true;video.play();}else{video.srcObject=null;video.src=url;video.play();}$('recordStatus').textContent='Previewing uploaded media.'};
$('photoMode').onclick=()=>{photoMode=true;$('photoMode').classList.add('active');$('videoMode').classList.remove('active');document.body.classList.remove('video-mode')};$('videoMode').onclick=()=>{photoMode=false;$('videoMode').classList.add('active');$('photoMode').classList.remove('active');document.body.classList.add('video-mode')};
$('galleryBtn').onclick=openGallery;$('galleryNav').onclick=openGallery;$('settingsBtn').onclick=()=>$('settings').classList.add('open');$('cameraNav').onclick=closePanels;$('lensesNav').onclick=()=>{closePanels();$('filters').scrollIntoView({behavior:'smooth'})};$$('[data-close]').forEach(b=>b.onclick=closePanels);$('clearGallery').onclick=()=>{if(confirm('Delete all saved Memories?')){localStorage.removeItem('leonlens_memories');renderGallery()}};
$('trackingToggle').onchange=e=>{tracking=e.target.checked;if(!tracking){faceResult=null;arCanvas.getContext('2d').clearRect(0,0,arCanvas.width,arCanvas.height)}};$('mirrorToggle').onchange=e=>{mirror=e.target.checked;document.body.classList.toggle('mirror',mirror)};$('tipsToggle').onchange=e=>$('gestureHint').style.display=e.target.checked?'block':'none';
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e});async function install(){if(installPrompt){installPrompt.prompt();await installPrompt.userChoice;installPrompt=null;}else{$('recordStatus').textContent='Use your browser menu and choose “Add to Home screen”.'}}$('install').onclick=install;$('install2').onclick=install;
$('startBtn').onclick=()=>{$('onboarding').classList.remove('show');startCamera()};$('skipIntro').onclick=()=>{$('onboarding').classList.remove('show');status.textContent='Tap Start Camera to begin';};
renderFilters();setLens('normal');document.body.classList.add('mirror');$('trackingToggle').checked=true;try{if(localStorage.getItem('leonlens_intro_seen'))$('onboarding').classList.remove('show');else localStorage.setItem('leonlens_intro_seen','1')}catch(e){}
if(!navigator.mediaDevices?.getUserMedia){status.textContent='Camera access requires a modern HTTPS browser.'}

// V6 social/account layer — local-first, optional Supabase cloud auth.
function openPanel(id){closePanels();$(id).classList.add('open')}
async function refreshAccount(){try{const u=await LeonCloud.user();if(u){$('accountName').textContent=u.email?.split('@')[0]||'LeonLens Creator';$('accountStatus').textContent='Cloud account connected';$('avatar').textContent=(u.email||'L')[0].toUpperCase();$('signOut').style.display='block';}else{$('accountName').textContent='Guest Creator';$('accountStatus').textContent=LeonCloud.ready()?'Not signed in':'Local mode';$('signOut').style.display=LeonCloud.ready()?'block':'none';}}catch(e){$('accountStatus').textContent='Local mode'}}
$('accountBtn').onclick=()=>{openPanel('account');refreshAccount()};
$('storiesBtn').onclick=()=>{openPanel('stories');renderStories()};$('storiesNav').onclick=()=>{openPanel('stories');renderStories()};
$('signIn').onclick=async()=>{try{const r=await LeonCloud.signIn($('email').value.trim(),$('password').value);if(r.error)throw r.error;await refreshAccount();$('recordStatus').textContent='Signed in.'}catch(e){$('recordStatus').textContent=e.message||'Sign in failed.'}};
$('signUp').onclick=async()=>{try{const r=await LeonCloud.signUp($('email').value.trim(),$('password').value);if(r.error)throw r.error;await refreshAccount();$('recordStatus').textContent='Account created. Check your email if confirmation is enabled.'}catch(e){$('recordStatus').textContent=e.message||'Could not create account.'}};
$('signOut').onclick=async()=>{await LeonCloud.signOut();await refreshAccount();$('recordStatus').textContent='Signed out.'};
async function shareLatest(){const items=JSON.parse(localStorage.getItem('leonlens_memories')||'[]');const item=items[0];if(!item){$('recordStatus').textContent='Capture something first.';return}try{const res=await fetch(item.data);const blob=await res.blob();const file=new File([blob],item.type==='image'?'leonlens.jpg':'leonlens.webm',{type:blob.type});if(navigator.canShare?.({files:[file]})){await navigator.share({title:'LeonLens',text:'Made with LeonLens',files:[file]})}else if(navigator.share){await navigator.share({title:'LeonLens',text:'Made with LeonLens'})}else{$('recordStatus').textContent='Sharing is not available in this browser.'}}catch(e){if(e.name!=='AbortError')$('recordStatus').textContent='Share cancelled or unavailable.'}}
function renderStories(){const row=$('storyRow');const items=JSON.parse(localStorage.getItem('leonlens_memories')||'[]').slice(0,8);row.innerHTML='';if(!items.length)return;items.forEach((item,i)=>{const d=document.createElement('div');d.className='story-bubble';const inner=item.type==='image'?`<img src="${item.data}">`:`<video src="${item.data}" muted playsinline></video>`;d.innerHTML=`<div class="story-ring">${inner}</div><span>${i===0?'Your story':'Memory '+(i+1)}</span>`;d.onclick=()=>shareLatest();row.appendChild(d)})}
// Add a share action to gallery header.
const shareButton=document.createElement('button');shareButton.className='text-btn';shareButton.textContent='Share';shareButton.onclick=shareLatest;$('gallery').querySelector('.panel-head').appendChild(shareButton);
refreshAccount();

/* =========================
   LEONLENS V7 — SOCIAL CLOUD
   ========================= */
(function initV7(){
  const top=$('.top-actions'), nav=$('.bottom-nav');
  if(!top||!nav)return;
  const addBtn=(parent,id,label,icon,cls='')=>{if($(id))return;const b=document.createElement('button');b.id=id;b.className=cls;b.setAttribute('aria-label',label);b.textContent=icon;parent.appendChild(b);return b};
  const profileBtn=addBtn(top,'profileBtn','Profile','◉');
  const discoverBtn=addBtn(top,'discoverBtn','Discover','⌕');
  const discoverNav=document.createElement('button');discoverNav.className='nav';discoverNav.id='discoverNav';discoverNav.innerHTML='⌕<span>Discover</span>';nav.insertBefore(discoverNav,nav.querySelector('#storiesNav'));

  const profilePanel=document.createElement('div');profilePanel.id='profilePanel';profilePanel.className='panel';profilePanel.innerHTML=`<div class="panel-head"><button class="close" data-close>×</button><h2>Profile</h2><button id="saveProfile" class="text-btn">Save</button></div><div class="v7-profile"><div class="big-avatar" id="profileAvatar">L</div><input id="profileUsername" class="field" maxlength="24" placeholder="username"><input id="profileDisplay" class="field" maxlength="40" placeholder="Display name"><textarea id="profileBio" class="field v7-textarea" maxlength="160" placeholder="Tell people about you"></textarea><div class="profile-stats"><div><b id="postCount">0</b><span>Posts</span></div><div><b id="followerCount">0</b><span>Followers</span></div><div><b id="followingCount">0</b><span>Following</span></div></div><p class="small-note" id="profileCloudNote">Local profile. Sign in to sync it across devices.</p></div>`;
document.body.appendChild(profilePanel);

  const discoverPanel=document.createElement('div');discoverPanel.id='discoverPanel';discoverPanel.className='panel';discoverPanel.innerHTML=`<div class="panel-head"><button class="close" data-close>×</button><h2>Discover</h2><button id="refreshDiscover" class="text-btn">Refresh</button></div><div class="discover-wrap"><div class="search-line"><input id="creatorSearch" class="field" placeholder="Search creators"><button id="creatorSearchBtn" class="search-btn">Search</button></div><div id="creatorResults" class="creator-results"></div><h3 class="section-title">Latest LeonLens</h3><div id="discoverFeed" class="discover-feed"></div><div id="discoverEmpty" class="empty">Connect a Supabase project to discover creators and cloud posts.</div></div>`;
document.body.appendChild(discoverPanel);

  const publishPanel=document.createElement('div');publishPanel.id='publishPanel';publishPanel.className='panel';publishPanel.innerHTML=`<div class="panel-head"><button class="close" data-close>×</button><h2>Publish</h2></div><div class="publish-wrap"><div id="publishPreview" class="publish-preview"></div><input id="publishCaption" class="field" maxlength="180" placeholder="Write a caption"><div class="publish-actions"><button id="publishPost" class="primary">Publish to Feed</button><button id="publishStory" class="ghost">Add to Story · 24h</button></div><p id="publishStatus" class="small-note">Cloud publishing requires a signed-in account and Supabase configuration.</p></div>`;
document.body.appendChild(publishPanel);

  function safe(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));}
  function localProfile(){try{return JSON.parse(localStorage.getItem('leonlens_profile')||'{}')}catch{return {}}}
  function saveLocalProfile(p){localStorage.setItem('leonlens_profile',JSON.stringify(p));}
  function initials(p){return (p?.display_name||p?.username||'L').trim().slice(0,1).toUpperCase()||'L'}
  async function openProfile(){openPanel('profilePanel');let p=localProfile();try{const cp=await LeonCloud.getProfile();if(cp)p=cp}catch{}$('profileUsername').value=p.username||'leonlens';$('profileDisplay').value=p.display_name||'LeonLens Creator';$('profileBio').value=p.bio||'';$('profileAvatar').textContent=initials(p);$('profileCloudNote').textContent=LeonCloud.ready()?'Cloud profile available when signed in.':'Local profile. Add Supabase config to sync across devices.';}
  profileBtn.onclick=openProfile;
  discoverBtn.onclick=()=>{openPanel('discoverPanel');loadDiscover()};
  discoverNav.onclick=()=>{openPanel('discoverPanel');loadDiscover()};

  $('saveProfile').onclick=async()=>{const p={username:$('profileUsername').value.trim().toLowerCase().replace(/[^a-z0-9_]/g,'').slice(0,24)||'leonlens',display_name:$('profileDisplay').value.trim()||'LeonLens Creator',bio:$('profileBio').value.trim()};saveLocalProfile(p);$('profileAvatar').textContent=initials(p);try{if(LeonCloud.ready()){const u=await LeonCloud.user();if(u){await LeonCloud.saveProfile(p);$('profileCloudNote').textContent='Profile synced to the cloud.'}else $('profileCloudNote').textContent='Saved locally. Sign in to sync it.'}}catch(e){$('profileCloudNote').textContent=e.message||'Saved locally; cloud sync failed.'}$('recordStatus').textContent='Profile saved.'};

  async function loadDiscover(){const feed=$('discoverFeed'),empty=$('discoverEmpty');feed.innerHTML='<div class="loading">Loading LeonLens…</div>';try{if(!LeonCloud.ready())throw Error('not-configured');const posts=await LeonCloud.discoverPosts();feed.innerHTML='';empty.style.display=posts.length?'none':'block';posts.forEach(post=>feed.appendChild(postCard(post)));if(!posts.length)empty.textContent='No cloud posts yet. Publish the first one.';}catch(e){feed.innerHTML='';empty.style.display='block';empty.textContent='Connect Supabase and sign in to unlock Discover.'}}
  function postCard(post){const el=document.createElement('article');el.className='post-card';const prof=post.profiles||{};const media=post.media_type==='video'?`<video src="${safe(post.media_url)}" controls playsinline preload="metadata"></video>`:`<img src="${safe(post.media_url)}" loading="lazy">`;el.innerHTML=`<div class="post-head"><div class="mini-avatar">${safe(initials(prof))}</div><div><b>${safe(prof.display_name||prof.username||'Creator')}</b><small>@${safe(prof.username||'creator')} · ${safe(post.lens||'Natural')}</small></div></div><div class="post-media">${media}</div><div class="post-body"><p>${safe(post.caption||'')}</p><button class="like-btn" data-post="${safe(post.id)}">♡ Like</button></div>`;el.querySelector('.like-btn').onclick=async()=>{try{const liked=await LeonCloud.toggleLike(post.id);el.querySelector('.like-btn').textContent=liked?'♥ Liked':'♡ Like'}catch(e){$('recordStatus').textContent=e.message||'Sign in to like posts.'}};return el}
  $('refreshDiscover').onclick=loadDiscover;
  $('creatorSearchBtn').onclick=searchCreators;
  $('creatorSearch').addEventListener('keydown',e=>{if(e.key==='Enter')searchCreators()});
  async function searchCreators(){const q=$('creatorSearch').value.trim(),box=$('creatorResults');if(!q){box.innerHTML='';return}box.innerHTML='<div class="loading">Searching…</div>';try{const rows=await LeonCloud.searchProfiles(q);box.innerHTML=rows.length?rows.map(r=>`<div class="creator-row"><div class="mini-avatar">${safe(initials(r))}</div><div class="creator-copy"><b>${safe(r.display_name||r.username)}</b><small>@${safe(r.username||'')}</small></div><button class="follow-btn" data-id="${safe(r.id)}">Follow</button></div>`).join(''):'<div class="empty compact">No creators found.</div>';box.querySelectorAll('.follow-btn').forEach(b=>b.onclick=async()=>{try{await LeonCloud.followUser(b.dataset.id);b.textContent='Following'}catch(e){$('recordStatus').textContent=e.message||'Sign in to follow creators.'}})}catch(e){box.innerHTML='<div class="empty compact">Creator search needs Supabase.</div>'}}

  let pendingPublish=null;
  function openPublish(item){pendingPublish=item;if(!item){$('publishPreview').innerHTML='';return}$('publishPreview').innerHTML=item.type==='video'?`<video src="${safe(item.data)}" controls playsinline></video>`:`<img src="${safe(item.data)}">`;$('publishCaption').value='';$('publishStatus').textContent=LeonCloud.ready()?'Sign in to publish this memory to the cloud.':'Add Supabase config to enable cloud publishing.';openPanel('publishPanel')}
  async function blobFromItem(item){const r=await fetch(item.data);return r.blob()}
  $('publishPost').onclick=async()=>{if(!pendingPublish)return;const btn=$('publishPost');btn.disabled=true;$('publishStatus').textContent='Uploading…';try{const u=await LeonCloud.user();if(!u)throw Error('Sign in first.');await LeonCloud.createPost(await blobFromItem(pendingPublish),pendingPublish.type,$('publishCaption').value,document.getElementById('lensName')?.textContent||'Natural');$('publishStatus').textContent='Published to Discover.';$('recordStatus').textContent='Published to LeonLens.'}catch(e){$('publishStatus').textContent=e.message||'Publish failed.'}finally{btn.disabled=false}};
  $('publishStory').onclick=async()=>{if(!pendingPublish)return;const btn=$('publishStory');btn.disabled=true;$('publishStatus').textContent='Publishing story…';try{const u=await LeonCloud.user();if(!u)throw Error('Sign in first.');await LeonCloud.createStory(await blobFromItem(pendingPublish),pendingPublish.type,document.getElementById('lensName')?.textContent||'Natural');$('publishStatus').textContent='Story published for 24 hours.';$('recordStatus').textContent='Story published.'}catch(e){$('publishStatus').textContent=e.message||'Story publish failed.'}finally{btn.disabled=false}};

  // Replace gallery renderer with V7 publish controls while keeping local-first behavior.
  const originalRenderGallery=window.renderGallery;
  window.renderGallery=function(){const grid=$('galleryGrid'),empty=$('emptyGallery');let items=[];try{items=JSON.parse(localStorage.getItem('leonlens_memories')||'[]')}catch{}grid.innerHTML='';empty.style.display=items.length?'none':'block';items.forEach(item=>{const el=document.createElement('div');el.className='gallery-item';el.innerHTML=item.type==='image'?`<img src="${item.data}" loading="lazy"><button class="delete-memory" aria-label="Delete">×</button><button class="publish-memory" aria-label="Publish">↑</button>`:`<video src="${item.data}" controls playsinline></video><button class="delete-memory" aria-label="Delete">×</button><button class="publish-memory" aria-label="Publish">↑</button>`;el.querySelector('.delete-memory').onclick=()=>{const next=items.filter(x=>x.id!==item.id);localStorage.setItem('leonlens_memories',JSON.stringify(next));renderGallery()};el.querySelector('.publish-memory').onclick=()=>openPublish(item);grid.appendChild(el)});};

  // Give Memories a simple cloud status button.
  const galleryHead=$('gallery')?.querySelector('.panel-head');if(galleryHead&&!galleryHead.querySelector('.cloud-status')){const b=document.createElement('button');b.className='text-btn cloud-status';b.textContent=LeonCloud.ready()?'Cloud':'Local';b.onclick=()=>openProfile();galleryHead.appendChild(b)}
  // Account panel gets a shortcut to the richer V7 profile.
  const accountCard=$('account')?.querySelector('.account-card');if(accountCard&&!accountCard.querySelector('.profile-shortcut')){const b=document.createElement('button');b.className='profile-shortcut';b.textContent='Edit profile';b.onclick=openProfile;accountCard.appendChild(b)}
  // V7 onboarding note.
  const note=$('recordStatus');if(note)note.textContent=LeonCloud.ready()?'Camera ready · Cloud social enabled':'Camera ready · Local-first mode';
})();
