/* LeonLens V7 cloud layer — optional Supabase Auth + profiles + social media. */
window.LEONLENS_CONFIG={supabaseUrl:'',supabasePublishableKey:'',storageBucket:'leonlens-media'};
let supabaseClient=null;
function cloudReady(){return !!(window.LEONLENS_CONFIG?.supabaseUrl&&window.LEONLENS_CONFIG?.supabasePublishableKey&&window.supabase?.createClient)}
function initCloud(){if(cloudReady()&&!supabaseClient){supabaseClient=window.supabase.createClient(LEONLENS_CONFIG.supabaseUrl,LEONLENS_CONFIG.supabasePublishableKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}})}return supabaseClient}
async function cloudUser(){const s=initCloud();if(!s)return null;const {data}=await s.auth.getUser();return data?.user||null}
async function cloudSignIn(email,password){const s=initCloud();if(!s)throw Error('Cloud login is not configured.');return s.auth.signInWithPassword({email,password})}
async function cloudSignUp(email,password){const s=initCloud();if(!s)throw Error('Cloud login is not configured.');return s.auth.signUp({email,password})}
async function cloudSignOut(){const s=initCloud();if(s)return s.auth.signOut({scope:'local'})}
async function getProfile(){const s=initCloud(),u=await cloudUser();if(!s||!u)return null;const {data,error}=await s.from('profiles').select('*').eq('id',u.id).maybeSingle();if(error)throw error;return data}
async function saveProfile(p){const s=initCloud(),u=await cloudUser();if(!s||!u)throw Error('Sign in to save a cloud profile.');const row={id:u.id,username:p.username,display_name:p.display_name,bio:p.bio,avatar_url:p.avatar_url||null,updated_at:new Date().toISOString()};const {data,error}=await s.from('profiles').upsert(row).select().single();if(error)throw error;return data}
async function searchProfiles(q){const s=initCloud();if(!s)throw Error('Cloud login is not configured.');const term=(q||'').trim().replace(/[%_]/g,'');if(!term)return [];const {data,error}=await s.from('profiles').select('id,username,display_name,bio,avatar_url').or(`username.ilike.%${term}%,display_name.ilike.%${term}%`).limit(20);if(error)throw error;return data||[]}
async function followUser(targetId){const s=initCloud(),u=await cloudUser();if(!s||!u)throw Error('Sign in to follow creators.');const {error}=await s.from('follows').upsert({follower_id:u.id,following_id:targetId},{onConflict:'follower_id,following_id'});if(error)throw error}
async function unfollowUser(targetId){const s=initCloud(),u=await cloudUser();if(!s||!u)throw Error('Sign in to follow creators.');const {error}=await s.from('follows').delete().eq('follower_id',u.id).eq('following_id',targetId);if(error)throw error}
async function isFollowing(targetId){const s=initCloud(),u=await cloudUser();if(!s||!u)return false;const {data}=await s.from('follows').select('follower_id').eq('follower_id',u.id).eq('following_id',targetId).maybeSingle();return !!data}
async function uploadMedia(blob,type){const s=initCloud(),u=await cloudUser();if(!s||!u)throw Error('Sign in to upload to cloud.');const ext=type==='video'?'webm':'jpg';const path=`${u.id}/${Date.now()}-${crypto.randomUUID()}.${ext}`;const {error:upError}=await s.storage.from(LEONLENS_CONFIG.storageBucket).upload(path,blob,{contentType:blob.type||`image/${ext}`,upsert:false});if(upError)throw upError;const {data}=s.storage.from(LEONLENS_CONFIG.storageBucket).getPublicUrl(path);return {path,url:data.publicUrl}}
async function createPost(media,type,caption,lens){const s=initCloud(),u=await cloudUser();if(!s||!u)throw Error('Sign in to publish.');const file=await uploadMedia(media,type);const {data,error}=await s.from('posts').insert({user_id:u.id,media_url:file.url,storage_path:file.path,media_type:type,caption:caption||'',lens:lens||'Natural'}).select().single();if(error)throw error;return data}
async function createStory(media,type,lens){const s=initCloud(),u=await cloudUser();if(!s||!u)throw Error('Sign in to publish stories.');const file=await uploadMedia(media,type);const expires=new Date(Date.now()+24*60*60*1000).toISOString();const {data,error}=await s.from('stories').insert({user_id:u.id,media_url:file.url,storage_path:file.path,media_type:type,lens:lens||'Natural',expires_at:expires}).select().single();if(error)throw error;return data}
async function discoverPosts(limit=24){const s=initCloud();if(!s)throw Error('Cloud login is not configured.');const {data,error}=await s.from('posts').select('id,user_id,media_url,media_type,caption,lens,created_at,profiles(username,display_name,avatar_url)').order('created_at',{ascending:false}).limit(limit);if(error)throw error;return data||[]}
async function toggleLike(postId){const s=initCloud(),u=await cloudUser();if(!s||!u)throw Error('Sign in to like posts.');const {data}=await s.from('likes').select('user_id').eq('post_id',postId).eq('user_id',u.id).maybeSingle();if(data){await s.from('likes').delete().eq('post_id',postId).eq('user_id',u.id);return false}const {error}=await s.from('likes').insert({post_id:postId,user_id:u.id});if(error)throw error;return true}
window.LeonCloud={ready:cloudReady,init:initCloud,user:cloudUser,signIn:cloudSignIn,signUp:cloudSignUp,signOut:cloudSignOut,getProfile,saveProfile,searchProfiles,followUser,unfollowUser,isFollowing,createPost,createStory,discoverPosts,toggleLike};
