/* LeonLens V10 — Social Network layer. Local-first UI with optional Supabase hooks. */
(()=>{
 const $=id=>document.getElementById(id); const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
 const LS={feed:'leonlens_v10_feed',friends:'leonlens_v10_friends',messages:'leonlens_v10_messages',notes:'leonlens_v10_notifications',stories:'leonlens_v10_stories'};
 const read=k=>{try{return JSON.parse(localStorage.getItem(k)||'[]')}catch{return[]}}; const write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
 function profile(){try{return JSON.parse(localStorage.getItem('leonlens_profile')||'{}')}catch{return{}}}
 function name(){const p=profile();return p.display_name||p.username||'You'}
 function initials(p=profile()){return ((p.display_name||p.username||'L').match(/\b\w/g)||['L']).slice(0,2).join('').toUpperCase()}
 function panel(id,title,body){if($(id))return;const d=document.createElement('div');d.id=id;d.className='panel';d.innerHTML=`<div class="panel-head"><button class="close" data-close>×</button><h2>${title}</h2></div>${body}`;document.body.appendChild(d);d.querySelector('[data-close]').onclick=()=>d.classList.remove('open');}
 function open(id){if(typeof openPanel==='function')openPanel(id);else $(id)?.classList.add('open')}
 function addTopNav(){const top=document.querySelector('.top-actions');if(top&&!$('socialBtn')){const b=document.createElement('button');b.id='socialBtn';b.textContent='♡';b.setAttribute('aria-label','Social');top.insertBefore(b,top.firstChild);b.onclick=()=>open('socialPanel')}
 const nav=document.querySelector('.bottom-nav');if(nav&&!$('socialNav')){const b=document.createElement('button');b.className='nav';b.id='socialNav';b.innerHTML='♡<span>Social</span>';nav.insertBefore(b,nav.lastElementChild);b.onclick=()=>open('socialPanel')}}
 function ensureUI(){panel('socialPanel','Social',`<div class="social-tabs"><button class="social-tab active" data-tab="feed">Discover</button><button class="social-tab" data-tab="friends">Friends</button><button class="social-tab" data-tab="messages">Messages</button><button class="social-tab" data-tab="alerts">Alerts</button></div><div id="socialContent"></div>`);panel('creatorPanel','Creator',`<div id="creatorContent"></div>`);document.querySelectorAll('.social-tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.social-tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderTab(b.dataset.tab)});addTopNav();renderTab('feed')}
 function demoPosts(){return [{id:'demo-1',creator:'LeonLens',handle:'@leonlens',caption:'Neon Pulse looks wild at night. ✨',lens:'Neon Pulse',emoji:'⚡',likes:218,comments:14,media:'gradient'},{id:'demo-2',creator:'MayaLens',handle:'@mayalens',caption:'Film Dust + golden hour.',lens:'Film Dust',emoji:'🎞️',likes:173,comments:9,media:'warm'},{id:'demo-3',creator:'Juno',handle:'@juno',caption:'Candy Pop test. What do you think?',lens:'Candy Pop',emoji:'🍭',likes:121,comments:6,media:'pink'}]}
 function feed(){return read(LS.feed).length?read(LS.feed):demoPosts()}
 function card(p){const liked=read('leonlens_v10_likes').includes(p.id);return `<article class="social-post"><div class="social-post-head"><div class="mini-avatar">${esc((p.creator||'L').slice(0,1).toUpperCase())}</div><div class="social-user"><b>${esc(p.creator)}</b><small>${esc(p.handle||'@creator')} · ${esc(p.lens||'Natural')}</small></div><button class="more-btn" data-creator="${esc(p.handle||'@creator')}">•••</button></div><div class="social-art ${esc(p.media||'gradient')}"><span>${esc(p.emoji||'✦')}</span></div><div class="social-actions"><button class="social-like ${liked?'liked':''}" data-id="${esc(p.id)}">${liked?'♥':'♡'} ${Number(p.likes||0)+(liked?1:0)}</button><button class="comment-open" data-id="${esc(p.id)}">💬 ${Number(p.comments||0)}</button><button class="share-social" data-id="${esc(p.id)}">↗ Share</button></div><p class="social-caption"><b>${esc(p.creator)}</b> ${esc(p.caption||'')}</p></article>`}
 function renderFeed(){const c=$('socialContent');c.innerHTML=`<div class="social-hero"><div><span class="eyebrow">LEONLENS V10</span><h3>Your camera. Your people.</h3><p>Discover creators, react, comment and share.</p></div><button class="primary" id="findCreators">Find creators</button></div><div class="feed-tools"><input id="feedSearch" class="field" placeholder="Search creators or lenses"><button class="search-btn" id="feedSearchBtn">Search</button></div><div id="feedGrid">${feed().map(card).join('')}</div>`;wireFeed();}
 function wireFeed(){const c=$('socialContent');c.querySelectorAll('.social-like').forEach(b=>b.onclick=()=>{let a=read('leonlens_v10_likes');const id=b.dataset.id;if(a.includes(id))a=a.filter(x=>x!==id);else a.push(id);write('leonlens_v10_likes',a);renderFeed()});c.querySelectorAll('.comment-open').forEach(b=>b.onclick=()=>openComments(b.dataset.id));c.querySelectorAll('.share-social').forEach(b=>b.onclick=()=>sharePost(b.dataset.id));c.querySelectorAll('.more-btn').forEach(b=>b.onclick=()=>openCreator(b.dataset.creator));$('findCreators').onclick=()=>renderTab('friends');$('feedSearchBtn').onclick=()=>searchFeed($('feedSearch').value);$('feedSearch').onkeydown=e=>{if(e.key==='Enter')searchFeed(e.target.value)};}
 function searchFeed(q){q=(q||'').trim().toLowerCase();const c=$('feedGrid');if(!c)return;const arr=feed().filter(p=>(p.creator+' '+p.handle+' '+p.lens+' '+p.caption).toLowerCase().includes(q));c.innerHTML=arr.length?arr.map(card).join(''):'<div class="empty">No posts found.</div>';wireFeed()}
 function renderFriends(){const creators=[...new Map(feed().map(p=>[p.handle,{name:p.creator,handle:p.handle,lens:p.lens}])).values()];const following=read(LS.friends);$('socialContent').innerHTML=`<div class="social-section"><h3>Find creators</h3><input id="creatorQ" class="field" placeholder="Search @username"><div id="creatorList" class="creator-list">${creators.map(c=>creatorRow(c,following)).join('')}</div><p class="small-note">With Supabase configured, this search can use real creator profiles and follows across devices.</p></div>`;const q=$('creatorQ');q.oninput=()=>{const v=q.value.toLowerCase();$('creatorList').innerHTML=creators.filter(c=>(c.name+c.handle).toLowerCase().includes(v)).map(c=>creatorRow(c,following)).join('');wireCreators()};wireCreators()}
 function creatorRow(c,following){const f=following.includes(c.handle);return `<div class="creator-row"><div class="mini-avatar">${esc(c.name.slice(0,1))}</div><div class="creator-copy"><b>${esc(c.name)}</b><small>${esc(c.handle)} · ${esc(c.lens||'Lens creator')}</small></div><button class="follow-btn ${f?'following':''}" data-handle="${esc(c.handle)}">${f?'Following':'Follow'}</button></div>`}
 function wireCreators(){document.querySelectorAll('.follow-btn').forEach(b=>b.onclick=async()=>{const h=b.dataset.handle;let a=read(LS.friends);if(a.includes(h)){a=a.filter(x=>x!==h);b.textContent='Follow';b.classList.remove('following')}else{a.push(h);b.textContent='Following';b.classList.add('following');pushNote(`You followed ${h}`)}write(LS.friends,a);try{if(window.LeonCloud?.ready()&&await LeonCloud.user()){const rows=await LeonCloud.searchProfiles(h.replace('@',''));const r=rows.find(x=>('@'+x.username).toLowerCase()===h.toLowerCase());if(r)await LeonCloud.isFollowing(r.id)}}catch(e){}})}
 function renderMessages(){const msgs=read(LS.messages);$('socialContent').innerHTML=`<div class="message-head"><h3>Messages</h3><button class="primary" id="newMessage">New message</button></div><div class="message-list">${msgs.length?msgs.map(m=>`<button class="message-row" data-name="${esc(m.name)}"><div class="mini-avatar">${esc(m.name[0])}</div><div><b>${esc(m.name)}</b><small>${esc(m.text)}</small></div><time>${esc(m.time)}</time></button>`).join(''):'<div class="empty">No messages yet. Start a conversation with a creator.</div>'}</div>`;$('newMessage').onclick=newMessage;document.querySelectorAll('.message-row').forEach(b=>b.onclick=()=>chat(b.dataset.name))}
 function newMessage(){const who=prompt('Creator username, e.g. @juno');if(!who)return;chat(who)}
 function chat(who){const text=prompt(`Message ${who}`);if(!text)return;const a=read(LS.messages);a.unshift({name:who.replace(/^@/,'@'),text,time:'now'});write(LS.messages,a.slice(0,50));pushNote(`Message sent to ${who}`);renderMessages()}
 function pushNote(text){const a=read(LS.notes);a.unshift({id:Date.now(),text,read:false,time:new Date().toLocaleTimeString([], {hour:'numeric',minute:'2-digit'})});write(LS.notes,a.slice(0,50))}
 function renderAlerts(){const a=read(LS.notes);$('socialContent').innerHTML=`<div class="alerts-head"><h3>Notifications</h3><button class="text-btn" id="clearAlerts">Clear</button></div>${a.length?a.map(n=>`<div class="alert-row ${n.read?'read':''}"><span class="alert-dot">${n.read?'✓':'●'}</span><div><b>${esc(n.text)}</b><small>${esc(n.time)}</small></div></div>`).join(''):'<div class="empty">You're all caught up.</div>'}`;$('clearAlerts').onclick=()=>{write(LS.notes,[]);renderAlerts()}}
 function renderTab(tab){if(tab==='feed')renderFeed();else if(tab==='friends')renderFriends();else if(tab==='messages')renderMessages();else renderAlerts()}
 function openComments(id){const comments=read('leonlens_v10_comments_'+id);const box=document.createElement('div');box.className='comment-sheet';box.innerHTML=`<div class="comment-card"><button class="preview-close">×</button><h3>Comments</h3><div class="comment-list">${comments.length?comments.map(c=>`<div class="comment"><div class="mini-avatar">${esc(c.name[0])}</div><div><b>${esc(c.name)}</b><p>${esc(c.text)}</p></div></div>`).join(''):'<div class="empty">Be the first to comment.</div>'}</div><div class="comment-compose"><input class="field" id="commentText" placeholder="Add a comment"><button class="primary" id="commentSend">Post</button></div></div>`;document.body.appendChild(box);box.querySelector('.preview-close').onclick=()=>box.remove();box.querySelector('#commentSend').onclick=()=>{const t=box.querySelector('#commentText').value.trim();if(!t)return;comments.push({name:name(),text:t});write('leonlens_v10_comments_'+id,comments);pushNote(`${name()} commented on a post`);box.remove();renderFeed()}}
 async function sharePost(id){try{if(navigator.share)await navigator.share({title:'LeonLens',text:`Check out this LeonLens post · ${id}`});else pushNote('Share link copied to your social workflow')}catch(e){if(e.name!=='AbortError')pushNote('Share cancelled')}}
 function openCreator(handle){const posts=feed().filter(p=>p.handle===handle);$('creatorContent').innerHTML=`<div class="creator-hero"><div class="big-avatar">${esc(handle.replace('@','')[0]||'L').toUpperCase()}</div><h3>${esc(handle)}</h3><p>LeonLens creator</p><div class="profile-stats"><div><b>${posts.length}</b><span>Posts</span></div><div><b>${posts.reduce((n,p)=>n+Number(p.likes||0),0)}</b><span>Likes</span></div><div><b>${posts.reduce((n,p)=>n+Number(p.comments||0),0)}</b><span>Comments</span></div></div></div>${posts.map(card).join('')}`;open('creatorPanel')}
 document.addEventListener('DOMContentLoaded',ensureUI);if(document.readyState!=='loading')ensureUI();
 window.LeonSocialV10={open:()=>open('socialPanel'),refresh:()=>renderTab('feed'),notify:pushNote};
})();
